ARG BASE_TAG="develop"
ARG BASE_IMAGE="core-ubuntu-focal"
FROM kasmweb/$BASE_IMAGE:$BASE_TAG
USER root

ENV HOME /home/kasm-default-profile
ENV STARTUPDIR /dockerstartup
ENV INST_SCRIPTS $STARTUPDIR/install
WORKDIR $HOME

######### Customize Container Here ###########

# Setup Env Variables
ENV SDK_VERSION=commandlinetools-linux-8512546_latest \
    ANDROID_BUILD_TOOLS_VERSION=34.0.0 \
    ANDROID_SDK_ROOT=/opt/android \
    JAVA_HOME=/home/kasm-user/android-studio/jbr \
    ANDROID_DOWNLOAD_PATH=/root \
    ANDROID_HOME=/opt/android \
    ANDROID_TOOL_HOME=/opt/android/cmdline-tools

ENV PATH=$PATH:${ANDROID_TOOL_HOME}/tools:${ANDROID_TOOL_HOME}/tools/bin
ENV PATH=$PATH:$ANDROID_HOME/platform-tools:$ANDROID_HOME/build-tools/$ANDROID_BUILD_TOOLS_VERSION

# Install Dependencies and Libraries

RUN dpkg --add-architecture i386 && \
    apt-get update && apt-get install --no-install-recommends -y \
        build-essential git neovim wget unzip sudo \
        libc6:i386 libncurses5:i386 libstdc++6:i386 lib32z1 libbz2-1.0:i386 \
        libxrender1 libxtst6 libxi6 libfreetype6 libxft2 zip unzip \
        qemu qemu-kvm libvirt-daemon-system libvirt-clients bridge-utils libnotify4 libglu1 libqt5widgets5 openjdk-11-jdk xvfb sshfs\
        && \
    apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*



# Install Android-Studio
# COPY provisioning/ndkTests.sh /usr/local/bin/ndkTests.sh
# COPY provisioning/51-android.rules /etc/udev/rules.d/51-android.rules

RUN wget https://redirector.gvt1.com/edgedl/android/studio/ide-zips/2023.1.1.27/android-studio-2023.1.1.27-linux.tar.gz && \
    tar -zxf android-studio-2023.1.1.27-linux.tar.gz && rm android-studio-2023.1.1.27-linux.tar.gz

RUN ln -s /studio-data/profile/AndroidStudio$ANDROID_STUDIO_VERSION .AndroidStudio$ANDROID_STUDIO_VERSION && \
    ln -s /studio-data/Android Android && \
    ln -s /studio-data/profile/android .android && \
    ln -s /studio-data/profile/java .java && \
    ln -s /studio-data/profile/gradle .gradle && \
    ANDROID_EMULATOR_USE_SYSTEM_LIBS=1 && \
    export PATH=$PATH:/studio-data/platform-tools/

RUN wget -O tools.zip https://dl.google.com/android/repository/${SDK_VERSION}.zip && \
unzip tools.zip && rm tools.zip && \
chmod a+x -R ${ANDROID_DOWNLOAD_PATH} && \
chown -R root:root ${ANDROID_DOWNLOAD_PATH} && \
mkdir -p ${ANDROID_TOOL_HOME} && \
mv cmdline-tools ${ANDROID_TOOL_HOME}/tools

# RUN echo y | sdkmanager "platform-tools" && \
#     echo y | sdkmanager "build-tools;$ANDROID_BUILD_TOOLS_VERSION"

# RUN yes | sdkmanager --licenses
# RUN sdkmanager "platforms;android-34"

# Update the desktop environment to be optimized for a single application
RUN cp $HOME/.config/xfce4/xfconf/single-application-xfce-perchannel-xml/* $HOME/.config/xfce4/xfconf/xfce-perchannel-xml/
RUN cp /usr/share/backgrounds/bg_kasm.png /usr/share/backgrounds/bg_default.png
RUN apt-get remove -y xfce4-panel

# Security modifications
COPY ./src/ubuntu/install/misc/single_app_security.sh $INST_SCRIPTS/misc/
RUN  bash $INST_SCRIPTS/misc/single_app_security.sh -t && rm -rf $INST_SCRIPTS/misc/
RUN echo "kasm-user ALL=(ALL:ALL) NOPASSWD:ALL" >> /etc/sudoers
RUN sudo usermod -aG root kasm-user
# COPY ./src/common/chrome-managed-policies/urlblocklist.json /etc/brave/policies/managed/urlblocklist.json

# Setup the custom startup script that will be invoked when the container starts
#ENV LAUNCH_URL  http://kasmweb.com

COPY ./src/ubuntu/install/android_studio_self/custom_startup.sh $STARTUPDIR/custom_startup.sh
RUN chmod +x $STARTUPDIR/custom_startup.sh

ENV KASM_RESTRICTED_FILE_CHOOSER=1
COPY ./src/ubuntu/install/gtk/ $INST_SCRIPTS/gtk/
RUN bash $INST_SCRIPTS/gtk/install_restricted_file_chooser.sh

######### End Customizations ###########

RUN chown 1000:0 $HOME
RUN $STARTUPDIR/set_user_permission.sh $HOME

ENV HOME /home/kasm-user
WORKDIR $HOME
RUN mkdir -p $HOME && chown -R 1000:0 $HOME

USER 1000

# Setup Env Variables
ENV SDK_VERSION=commandlinetools-linux-8512546_latest \
    ANDROID_BUILD_TOOLS_VERSION=34.0.0 \
    ANDROID_SDK_ROOT=/opt/android \
    JAVA_HOME=/home/kasm-user/android-studio/jbr \
    ANDROID_DOWNLOAD_PATH=/root \
    ANDROID_HOME=/opt/android \
    ANDROID_TOOL_HOME=/opt/android/cmdline-tools

ENV PATH=$PATH:${ANDROID_TOOL_HOME}/tools:${ANDROID_TOOL_HOME}/tools/bin
ENV PATH=$PATH:$ANDROID_HOME/platform-tools:$ANDROID_HOME/build-tools/$ANDROID_BUILD_TOOLS_VERSION
